import = ["/home/john/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 13

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "n"
mods = "Control|Shift"
