theme = "monokai_pro_machine"

[editor]
mouse = false
rulers = [81]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.indent-guides]
render = false
