[[language]]
name = "ruby"
language-server = { command = "standardrb", args = ["--lsp"] }
# https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration
# formatter = { command = "standardrb", args = ["--stdin", "foo.rb", "--fix", "--stderr"] }
auto-format = true
